/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const applicationClientDetailsNiNumberMin = 9;
export const applicationClientDetailsNiNumberMax = 9;

export const applicationClientDetailsNiNumberRegExp = new RegExp(
  "[A-CEGHJ-NOPR-TW-Z]{2}[0-9]{6}[ABCDs]{1}",
);
export const applicationClientDetailsAddressCountryMax = 2;

export const Application = zod.object({
  id: zod.uuid(),
  applicationRefNumber: zod.string().optional(),
  individualLegalAidNumber: zod.uuid(),
  providerFirmCode: zod.string(),
  providerOfficeCode: zod.string(),
  meansAssessmentId: zod.uuid().optional(),
  clientDetails: zod.object({
    id: zod.uuid().optional(),
    firstName: zod.string(),
    lastName: zod.string(),
    dateOfBirth: zod.iso.date(),
    niNumber: zod
      .string()
      .min(applicationClientDetailsNiNumberMin)
      .max(applicationClientDetailsNiNumberMax)
      .regex(applicationClientDetailsNiNumberRegExp)
      .optional(),
    hasFixedAddress: zod.boolean(),
    address: zod
      .object({
        id: zod.uuid().optional(),
        addressLine1: zod.string(),
        addressLine2: zod.string().optional(),
        addressLine3: zod.string().optional(),
        addressLine4: zod.string().optional(),
        townOrCity: zod.string().optional(),
        postCode: zod.string().optional(),
        county: zod.string().optional(),
        country: zod.string().max(applicationClientDetailsAddressCountryMax),
        createdAt: zod.iso.datetime({ offset: true }).optional(),
        modifiedAt: zod.iso.datetime({ offset: true }).optional(),
      })
      .optional(),
    createdAt: zod.iso.datetime({ offset: true }).optional(),
    modifiedAt: zod.iso.datetime({ offset: true }).optional(),
  }),
  applicationState: zod.enum(["DRAFT", "COMPLETED"]),
  declaration: zod
    .object({
      id: zod.uuid().optional(),
      declarationConfirmation: zod.boolean().optional(),
      dateSigned: zod.iso.date().optional(),
      createdAt: zod.iso.datetime({ offset: true }).optional(),
      createdBy: zod.string().optional(),
      modifiedAt: zod.iso.datetime({ offset: true }).optional(),
      modifiedBy: zod.string().optional(),
    })
    .optional(),
  evidence: zod
    .object({
      id: zod.uuid().optional(),
      payeIncomeEvidence: zod.boolean().optional(),
      otherIncomeEvidence: zod.boolean().optional(),
      housingCostsEvidence: zod.boolean().optional(),
      capitalEvidence: zod.boolean().optional(),
      createdAt: zod.iso.datetime({ offset: true }).optional(),
      createdBy: zod.string().optional(),
      modifiedAt: zod.iso.datetime({ offset: true }).optional(),
      modifiedBy: zod.string().optional(),
    })
    .optional(),
  eligibility: zod
    .object({
      data: zod.looseObject({}).optional(),
      result: zod.looseObject({}).optional(),
    })
    .optional(),
  reasonForReapplication: zod.string().optional(),
  meansAssessmentRequired: zod.boolean().optional(),
  typeOfNonMeans: zod.boolean().optional(),
  contribution: zod.string().optional(),
  scopingQuestions: zod.looseObject({}).optional(),
  applicationType: zod.string(),
  createdAt: zod.iso.datetime({ offset: true }),
  createdBy: zod.string(),
  modifiedAt: zod.iso.datetime({ offset: true }),
  modifiedBy: zod.string(),
});

export type Application = zod.input<typeof Application>;
export type ApplicationOutput = zod.output<typeof Application>;
