/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const Declaration = zod.object({
  id: zod.uuid().optional(),
  declarationConfirmation: zod.boolean().optional(),
  dateSigned: zod.iso.date().optional(),
  createdAt: zod.iso.datetime({ offset: true }).optional(),
  createdBy: zod.string().optional(),
  modifiedAt: zod.iso.datetime({ offset: true }).optional(),
  modifiedBy: zod.string().optional(),
});

export type Declaration = zod.input<typeof Declaration>;
export type DeclarationOutput = zod.output<typeof Declaration>;
