/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const Evidence = zod.object({
  id: zod.uuid().optional(),
  payeIncomeEvidence: zod.boolean().optional(),
  otherIncomeEvidence: zod.boolean().optional(),
  housingCostsEvidence: zod.boolean().optional(),
  capitalEvidence: zod.boolean().optional(),
  createdAt: zod.iso.datetime({ offset: true }).optional(),
  createdBy: zod.string().optional(),
  modifiedAt: zod.iso.datetime({ offset: true }).optional(),
  modifiedBy: zod.string().optional(),
});

export type Evidence = zod.input<typeof Evidence>;
export type EvidenceOutput = zod.output<typeof Evidence>;
