/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const NotFoundResponse = zod.object({
  type: zod.url().describe("URI reference identifying the problem type"),
  title: zod.string().describe("Human-readable summary of the problem type"),
  status: zod.int().describe("HTTP status code"),
  detail: zod
    .string()
    .optional()
    .describe("Human-readable explanation specific to this occurrence"),
  instance: zod
    .url()
    .optional()
    .describe("URI reference identifying the specific occurrence"),
  reason: zod
    .string()
    .optional()
    .describe(
      "Machine-readable code identifying the exact violation, e.g. APPLICATION_NOT_FOUND",
    ),
});

export type NotFoundResponse = zod.input<typeof NotFoundResponse>;
export type NotFoundResponseOutput = zod.output<typeof NotFoundResponse>;
