/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const UpdateApplicationStatusBody = zod.object({
  applicationState: zod.enum(["DRAFT", "COMPLETED"]),
  eTag: zod.int().describe("ETag value for optimistic concurrency control"),
});

export type UpdateApplicationStatusBody = zod.input<
  typeof UpdateApplicationStatusBody
>;
export type UpdateApplicationStatusBodyOutput = zod.output<
  typeof UpdateApplicationStatusBody
>;
