/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const UpdateApplicationDeclarationBody = zod.object({
  declarationConfirmation: zod.boolean(),
  dateSigned: zod.iso.date(),
});

export type UpdateApplicationDeclarationBody = zod.input<
  typeof UpdateApplicationDeclarationBody
>;
export type UpdateApplicationDeclarationBodyOutput = zod.output<
  typeof UpdateApplicationDeclarationBody
>;
