/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const UpdateEvidenceRequestBody = zod.object({
  evidenceExemptionCode: zod.string().optional(),
  evidenceExemptionReason: zod.string().optional(),
  incomeEvidenceChecklist: zod.looseObject({}).optional(),
  expenditureCapitalEvidenceChecklist: zod.looseObject({}).optional(),
});

export type UpdateEvidenceRequestBody = zod.input<
  typeof UpdateEvidenceRequestBody
>;
export type UpdateEvidenceRequestBodyOutput = zod.output<
  typeof UpdateEvidenceRequestBody
>;
