/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const UpdateApplicationEvidenceBody = zod.object({
  evidenceExemptionCode: zod.string().optional(),
  evidenceExemptionReason: zod.string().optional(),
  incomeEvidenceChecklist: zod.looseObject({}).optional(),
  expenditureCapitalEvidenceChecklist: zod.looseObject({}).optional(),
});

export type UpdateApplicationEvidenceBody = zod.input<
  typeof UpdateApplicationEvidenceBody
>;
export type UpdateApplicationEvidenceBodyOutput = zod.output<
  typeof UpdateApplicationEvidenceBody
>;
