/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const UpdateApplicationStatusRequestBody = zod.object({
  applicationState: zod.enum(["DRAFT", "COMPLETED"]),
  eTag: zod.int().describe("ETag value for optimistic concurrency control"),
});

export type UpdateApplicationStatusRequestBody = zod.input<
  typeof UpdateApplicationStatusRequestBody
>;
export type UpdateApplicationStatusRequestBodyOutput = zod.output<
  typeof UpdateApplicationStatusRequestBody
>;
