/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const UpdateDeclarationRequestBody = zod.object({
  declarationConfirmation: zod.boolean(),
  dateSigned: zod.iso.date(),
});

export type UpdateDeclarationRequestBody = zod.input<
  typeof UpdateDeclarationRequestBody
>;
export type UpdateDeclarationRequestBodyOutput = zod.output<
  typeof UpdateDeclarationRequestBody
>;
