/**
 * Generated by Orval
 * Do not edit manually.
 * Provider Details API r1
 * OpenAPI spec version: 0.27.2
 */
import type { ProviderFirmOfficeListDto } from "#/api/clients/pda/model/providerFirmOfficeListDto.zod.gen.js";

import config from "#/config.js";

export type getAllProviderOfficesResponse200 = {
  data: ProviderFirmOfficeListDto;
  status: 200;
};

export type getAllProviderOfficesResponse204 = {
  data: void;
  status: 204;
};

export type getAllProviderOfficesResponse409 = {
  data: void;
  status: 409;
};

export type getAllProviderOfficesResponse500 = {
  data: void;
  status: 500;
};

export type getAllProviderOfficesResponseSuccess = (
  getAllProviderOfficesResponse200 | getAllProviderOfficesResponse204
) & {
  headers: Headers;
};
export type getAllProviderOfficesResponseError = (
  getAllProviderOfficesResponse409 | getAllProviderOfficesResponse500
) & {
  headers: Headers;
};

export type getAllProviderOfficesResponse =
  getAllProviderOfficesResponseSuccess | getAllProviderOfficesResponseError;

export const getGetAllProviderOfficesUrl = (firmId: number) => {
  return `${config.api.pda.baseUrl}/provider-firms/${firmId}/provider-offices`;
};

/**
 *     Business Rules: - Firm is not end dated.
 *                     - Firm is of type Legal Services Provider / Advocate / Chambers.
 *                     - Firms of type Individual / QM Provider are NOT considered.
 *                     - Firm Office is not end dated.
 *                     - This DOES NOT check if a provider office has an active contract.
 * @summary Get all provider(firm) offices(sites) details based on a provider(firm) id.
 */
export const getAllProviderOffices = async (
  firmId: number,
  options?: RequestInit,
): Promise<getAllProviderOfficesResponse> => {
  const res = await fetch(getGetAllProviderOfficesUrl(firmId), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getAllProviderOfficesResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getAllProviderOfficesResponse;
};
