/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import type { Application } from "#/api/clients/rcw/model/application.zod.gen.js";

import type { Applications } from "#/api/clients/rcw/model/applications.zod.gen.js";

import type { BadRequestResponse } from "#/api/clients/rcw/model/badRequestResponse.zod.gen.js";

import type { ConflictResponse } from "#/api/clients/rcw/model/conflictResponse.zod.gen.js";

import type { CreateApplicationRequestBody } from "#/api/clients/rcw/model/createApplicationRequestBody.zod.gen.js";

import type { CreateApplicationResponseBody } from "#/api/clients/rcw/model/createApplicationResponseBody.zod.gen.js";

import type { ForbiddenResponse } from "#/api/clients/rcw/model/forbiddenResponse.zod.gen.js";

import type { GetApplicationsParams } from "#/api/clients/rcw/model/getApplicationsParams.zod.gen.js";

import type { InternalServerErrorResponse } from "#/api/clients/rcw/model/internalServerErrorResponse.zod.gen.js";

import type { NotFoundResponse } from "#/api/clients/rcw/model/notFoundResponse.zod.gen.js";

import type { UnauthorizedResponse } from "#/api/clients/rcw/model/unauthorizedResponse.zod.gen.js";

import type { UpdateApplicationStatusRequestBody } from "#/api/clients/rcw/model/updateApplicationStatusRequestBody.zod.gen.js";

import type { UpdateEvidenceRequestBody } from "#/api/clients/rcw/model/updateEvidenceRequestBody.zod.gen.js";

import type { UpdateMeansDataRequestBody } from "#/api/clients/rcw/model/updateMeansDataRequestBody.zod.gen.js";

import config from "#/config.js";

export type getApplicationsResponse200 = {
  data: Applications;
  status: 200;
};

export type getApplicationsResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type getApplicationsResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type getApplicationsResponse403 = {
  data: ForbiddenResponse;
  status: 403;
};

export type getApplicationsResponse500 = {
  data: InternalServerErrorResponse;
  status: 500;
};

export type getApplicationsResponseSuccess = getApplicationsResponse200 & {
  headers: Headers;
};
export type getApplicationsResponseError = (
  | getApplicationsResponse400
  | getApplicationsResponse401
  | getApplicationsResponse403
  | getApplicationsResponse500
) & {
  headers: Headers;
};

export type getApplicationsResponse =
  getApplicationsResponseSuccess | getApplicationsResponseError;

export const getGetApplicationsUrl = (params?: GetApplicationsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `${config.api.rcw.baseUrl}/api/v1/applications?${stringifiedParams}`
    : `${config.api.rcw.baseUrl}/api/v1/applications`;
};

/**
 * @summary Get all applications
 */
export const getApplications = async (
  params?: GetApplicationsParams,
  options?: RequestInit,
): Promise<getApplicationsResponse> => {
  const res = await fetch(getGetApplicationsUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApplicationsResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getApplicationsResponse;
};

export type createApplicationResponse201 = {
  data: CreateApplicationResponseBody;
  status: 201;
};

export type createApplicationResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type createApplicationResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type createApplicationResponse403 = {
  data: ForbiddenResponse;
  status: 403;
};

export type createApplicationResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type createApplicationResponse500 = {
  data: InternalServerErrorResponse;
  status: 500;
};

export type createApplicationResponseSuccess = createApplicationResponse201 & {
  headers: Headers;
};
export type createApplicationResponseError = (
  | createApplicationResponse400
  | createApplicationResponse401
  | createApplicationResponse403
  | createApplicationResponse404
  | createApplicationResponse500
) & {
  headers: Headers;
};

export type createApplicationResponse =
  createApplicationResponseSuccess | createApplicationResponseError;

export const getCreateApplicationUrl = () => {
  return `${config.api.rcw.baseUrl}/api/v1/applications`;
};

/**
 * @summary Create an application
 */
export const createApplication = async (
  createApplicationRequestBody?: CreateApplicationRequestBody,
  options?: RequestInit,
): Promise<createApplicationResponse> => {
  const res = await fetch(getCreateApplicationUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createApplicationRequestBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createApplicationResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as createApplicationResponse;
};

export type getApplicationResponse200 = {
  data: Application;
  status: 200;
};

export type getApplicationResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type getApplicationResponse403 = {
  data: ForbiddenResponse;
  status: 403;
};

export type getApplicationResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type getApplicationResponse500 = {
  data: InternalServerErrorResponse;
  status: 500;
};

export type getApplicationResponseSuccess = getApplicationResponse200 & {
  headers: Headers;
};
export type getApplicationResponseError = (
  | getApplicationResponse401
  | getApplicationResponse403
  | getApplicationResponse404
  | getApplicationResponse500
) & {
  headers: Headers;
};

export type getApplicationResponse =
  getApplicationResponseSuccess | getApplicationResponseError;

export const getGetApplicationUrl = (id: string) => {
  return `${config.api.rcw.baseUrl}/api/v1/applications/${id}`;
};

/**
 * @summary Get application by ID
 */
export const getApplication = async (
  id: string,
  options?: RequestInit,
): Promise<getApplicationResponse> => {
  const res = await fetch(getGetApplicationUrl(id), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApplicationResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getApplicationResponse;
};

export type updateApplicationEvidenceResponse204 = {
  data: void;
  status: 204;
};

export type updateApplicationEvidenceResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type updateApplicationEvidenceResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type updateApplicationEvidenceResponse403 = {
  data: ForbiddenResponse;
  status: 403;
};

export type updateApplicationEvidenceResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type updateApplicationEvidenceResponse409 = {
  data: ConflictResponse;
  status: 409;
};

export type updateApplicationEvidenceResponse500 = {
  data: InternalServerErrorResponse;
  status: 500;
};

export type updateApplicationEvidenceResponseSuccess =
  updateApplicationEvidenceResponse204 & {
    headers: Headers;
  };
export type updateApplicationEvidenceResponseError = (
  | updateApplicationEvidenceResponse400
  | updateApplicationEvidenceResponse401
  | updateApplicationEvidenceResponse403
  | updateApplicationEvidenceResponse404
  | updateApplicationEvidenceResponse409
  | updateApplicationEvidenceResponse500
) & {
  headers: Headers;
};

export type updateApplicationEvidenceResponse =
  | updateApplicationEvidenceResponseSuccess
  | updateApplicationEvidenceResponseError;

export const getUpdateApplicationEvidenceUrl = (id: string) => {
  return `${config.api.rcw.baseUrl}/api/v1/applications/${id}/evidence`;
};

/**
 * @summary Update the evidence data for an application
 */
export const updateApplicationEvidence = async (
  id: string,
  updateEvidenceRequestBody: UpdateEvidenceRequestBody,
  options?: RequestInit,
): Promise<updateApplicationEvidenceResponse> => {
  const res = await fetch(getUpdateApplicationEvidenceUrl(id), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateEvidenceRequestBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateApplicationEvidenceResponse["data"] = body
    ? JSON.parse(body)
    : undefined;
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as updateApplicationEvidenceResponse;
};

export type updateApplicationMeansResponse204 = {
  data: void;
  status: 204;
};

export type updateApplicationMeansResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type updateApplicationMeansResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type updateApplicationMeansResponse403 = {
  data: ForbiddenResponse;
  status: 403;
};

export type updateApplicationMeansResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type updateApplicationMeansResponse409 = {
  data: ConflictResponse;
  status: 409;
};

export type updateApplicationMeansResponse500 = {
  data: InternalServerErrorResponse;
  status: 500;
};

export type updateApplicationMeansResponseSuccess =
  updateApplicationMeansResponse204 & {
    headers: Headers;
  };
export type updateApplicationMeansResponseError = (
  | updateApplicationMeansResponse400
  | updateApplicationMeansResponse401
  | updateApplicationMeansResponse403
  | updateApplicationMeansResponse404
  | updateApplicationMeansResponse409
  | updateApplicationMeansResponse500
) & {
  headers: Headers;
};

export type updateApplicationMeansResponse =
  updateApplicationMeansResponseSuccess | updateApplicationMeansResponseError;

export const getUpdateApplicationMeansUrl = (id: string) => {
  return `${config.api.rcw.baseUrl}/api/v1/applications/${id}/means`;
};

/**
 * @summary Update the means data for an application
 */
export const updateApplicationMeans = async (
  id: string,
  updateMeansDataRequestBody: UpdateMeansDataRequestBody,
  options?: RequestInit,
): Promise<updateApplicationMeansResponse> => {
  const res = await fetch(getUpdateApplicationMeansUrl(id), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateMeansDataRequestBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateApplicationMeansResponse["data"] = body
    ? JSON.parse(body)
    : undefined;
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as updateApplicationMeansResponse;
};

export type updateApplicationStatusResponse204 = {
  data: void;
  status: 204;
};

export type updateApplicationStatusResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type updateApplicationStatusResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type updateApplicationStatusResponse403 = {
  data: ForbiddenResponse;
  status: 403;
};

export type updateApplicationStatusResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type updateApplicationStatusResponse409 = {
  data: ConflictResponse;
  status: 409;
};

export type updateApplicationStatusResponse500 = {
  data: InternalServerErrorResponse;
  status: 500;
};

export type updateApplicationStatusResponseSuccess =
  updateApplicationStatusResponse204 & {
    headers: Headers;
  };
export type updateApplicationStatusResponseError = (
  | updateApplicationStatusResponse400
  | updateApplicationStatusResponse401
  | updateApplicationStatusResponse403
  | updateApplicationStatusResponse404
  | updateApplicationStatusResponse409
  | updateApplicationStatusResponse500
) & {
  headers: Headers;
};

export type updateApplicationStatusResponse =
  updateApplicationStatusResponseSuccess | updateApplicationStatusResponseError;

export const getUpdateApplicationStatusUrl = (id: string) => {
  return `${config.api.rcw.baseUrl}/api/v1/applications/${id}/status`;
};

/**
 * @summary Update the application status
 */
export const updateApplicationStatus = async (
  id: string,
  updateApplicationStatusRequestBody: UpdateApplicationStatusRequestBody,
  options?: RequestInit,
): Promise<updateApplicationStatusResponse> => {
  const res = await fetch(getUpdateApplicationStatusUrl(id), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateApplicationStatusRequestBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateApplicationStatusResponse["data"] = body
    ? JSON.parse(body)
    : undefined;
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as updateApplicationStatusResponse;
};
