/**
 * Generated by Orval
 * Do not edit manually.
 * Provider Details API r1
 * OpenAPI spec version: 0.27.2
 */
import type { ProviderFirmOfficeListDto } from "#/api/clients/pda/model/providerFirmOfficeListDto.zod";

import { HttpResponse, http } from "msw";
import type { RequestHandlerOptions } from "msw";

import { getGetAllProviderOfficesResponseMock } from "../../fakers/provider-firms-endpoints/provider-firms-endpoints.faker.gen.gen.js";

export { getGetAllProviderOfficesResponseMock } from "../../fakers/provider-firms-endpoints/provider-firms-endpoints.faker.gen.gen.js";

export type KeysWithNull<O> = {
  [K in keyof O]-?: null extends O[K] ? K : never;
}[keyof O];

export type MockWithNullableOverrides<
  T,
  O extends Partial<T>,
  M extends Record<keyof T, unknown>,
> = Omit<M, Extract<KeysWithNull<O>, keyof T>> & {
  [K in Extract<KeysWithNull<O>, keyof T>]: M[K] | null;
};

export type ProviderFirmOfficeListDtoMock = {
  [K in keyof Required<NonNullable<ProviderFirmOfficeListDto>>]: NonNullable<
    Required<NonNullable<ProviderFirmOfficeListDto>>[K]
  >;
};

export const getGetAllProviderOfficesMockHandler = (
  overrideResponse?:
    | ProviderFirmOfficeListDto
    | void
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) =>
        | Promise<ProviderFirmOfficeListDto | void>
        | ProviderFirmOfficeListDto
        | void),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/provider-firms/:firmId/provider-offices",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      const resolvedBody =
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetAllProviderOfficesResponseMock();
      return resolvedBody === undefined
        ? new HttpResponse(null, { status: 204 })
        : HttpResponse.json(resolvedBody, { status: 200 });
    },
    options,
  );
};
export const getProviderFirmsEndpointsMock = () => [
  getGetAllProviderOfficesMockHandler(),
];
