/**
 * Generated by Orval
 * Do not edit manually.
 * Provider Details API r1
 * OpenAPI spec version: 0.27.2
 */
import * as zod from "zod";

export const ProviderFirmOfficeListDto = zod.object({
  firm: zod
    .object({
      firmNumber: zod.string().optional(),
      firmId: zod.int().optional(),
      ccmsFirmId: zod.int().optional(),
      parentFirmId: zod.int().optional(),
      firmName: zod.string().optional(),
      firmType: zod.string().optional(),
      constitutionalStatus: zod.string().optional(),
      solicitorAdvocateYN: zod.string().optional(),
      advocateLevel: zod.string().optional(),
      barCouncilRoll: zod.string().optional(),
      companyHouseNumber: zod.string().optional(),
    })
    .optional(),
  offices: zod
    .array(
      zod.object({
        firmOfficeId: zod.int().optional(),
        ccmsFirmOfficeId: zod.int().optional(),
        firmOfficeCode: zod.string().optional(),
        officeName: zod.string().optional(),
        officeCodeAlt: zod.string().optional(),
        type: zod.string().optional(),
        addressLine1: zod.string().optional(),
        addressLine2: zod.string().optional(),
        addressLine3: zod.string().optional(),
        addressLine4: zod.string().optional(),
        city: zod.string().optional(),
        county: zod.string().optional(),
        postCode: zod.string().optional(),
        dxCentre: zod.string().optional(),
        dxNumber: zod.string().optional(),
        telephoneAreaCode: zod.string().optional(),
        telephoneNumber: zod.string().optional(),
        faxAreaCode: zod.string().optional(),
        faxNumber: zod.string().optional(),
        emailAddress: zod.string().optional(),
        vatRegistrationNumber: zod.string().optional(),
        headOffice: zod.string().optional(),
        creationDate: zod.iso.date().optional(),
        lscRegion: zod.string().optional(),
        lscBidZone: zod.string().optional(),
        lscAreaOffice: zod.string().optional(),
        cjsForceName: zod.string().optional(),
        localAuthority: zod.string().optional(),
        policeStationAreaName: zod.string().optional(),
        dutySolicitorAreaName: zod.string().optional(),
      }),
    )
    .optional(),
});

export type ProviderFirmOfficeListDto = zod.input<
  typeof ProviderFirmOfficeListDto
>;
export type ProviderFirmOfficeListDtoOutput = zod.output<
  typeof ProviderFirmOfficeListDto
>;
