/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import type { Application } from "#/api/clients/rcw/model/application.zod.gen.js";

import type { Applications } from "#/api/clients/rcw/model/applications.zod.gen.js";

import type { CreateApplicationResponseBody } from "#/api/clients/rcw/model/createApplicationResponseBody.zod.gen.js";

import { faker } from "@faker-js/faker";

export type KeysWithNull<O> = {
  [K in keyof O]-?: null extends O[K] ? K : never;
}[keyof O];

export type MockWithNullableOverrides<
  T,
  O extends Partial<T>,
  M extends Record<keyof T, unknown>,
> = Omit<M, Extract<KeysWithNull<O>, keyof T>> & {
  [K in Extract<KeysWithNull<O>, keyof T>]: M[K] | null;
};

export type ApplicationsMock = Applications;

export type CreateApplicationResponseBodyMock = {
  [
    K in keyof Required<NonNullable<CreateApplicationResponseBody>>
  ]: NonNullable<Required<NonNullable<CreateApplicationResponseBody>>[K]>;
};

export type ApplicationMock = {
  [K in keyof Required<NonNullable<Application>>]: NonNullable<
    Required<NonNullable<Application>>[K]
  >;
};

export const getGetApplicationsResponseMock = (): ApplicationsMock =>
  Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.string.uuid(),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    applicationRefNumber: faker.string.alpha({ length: { min: 10, max: 20 } }),
    modifiedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
  }));

export const getCreateApplicationResponseMock = <
  O extends Partial<Extract<CreateApplicationResponseBody, object>> = {},
>(
  overrideResponse?: O,
): MockWithNullableOverrides<
  CreateApplicationResponseBody,
  O,
  CreateApplicationResponseBodyMock
> =>
  ({
    id: faker.string.uuid(),
    ...overrideResponse,
  }) as MockWithNullableOverrides<
    CreateApplicationResponseBody,
    O,
    CreateApplicationResponseBodyMock
  >;

export const getGetApplicationResponseMock = <
  O extends Partial<Extract<Application, object>> = {},
>(
  overrideResponse?: O,
): MockWithNullableOverrides<Application, O, ApplicationMock> =>
  ({
    id: faker.string.uuid(),
    applicationRefNumber: faker.string.alpha({ length: { min: 10, max: 20 } }),
    individualLegalAidNumber: faker.string.uuid(),
    providerFirmCode: faker.string.alpha({ length: { min: 10, max: 20 } }),
    providerOfficeCode: faker.string.alpha({ length: { min: 10, max: 20 } }),
    meansAssessmentId: faker.string.uuid(),
    clientDetails: {
      id: faker.string.uuid(),
      firstName: faker.string.alpha({ length: { min: 10, max: 20 } }),
      lastName: faker.string.alpha({ length: { min: 10, max: 20 } }),
      dateOfBirth: faker.date.past().toISOString().slice(0, 10),
      niNumber: faker.helpers.fromRegExp(
        "[A-CEGHJ-NOPR-TW-Z]{2}[0-9]{6}[ABCDs]{1}",
      ),
      hasFixedAddress: faker.datatype.boolean(),
      address: {
        id: faker.string.uuid(),
        addressLine1: faker.string.alpha({ length: { min: 10, max: 20 } }),
        addressLine2: faker.string.alpha({ length: { min: 10, max: 20 } }),
        addressLine3: faker.string.alpha({ length: { min: 10, max: 20 } }),
        addressLine4: faker.string.alpha({ length: { min: 10, max: 20 } }),
        townOrCity: faker.string.alpha({ length: { min: 10, max: 20 } }),
        postCode: faker.string.alpha({ length: { min: 10, max: 20 } }),
        county: faker.string.alpha({ length: { min: 10, max: 20 } }),
        country: faker.string.alpha({ length: { min: 2, max: 2 } }),
        createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
        modifiedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
      },
      createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
      modifiedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
    },
    applicationState: faker.helpers.arrayElement([
      "DRAFT",
      "COMPLETED",
    ] as const),
    declaration: {
      id: faker.string.uuid(),
      declarationConfirmation: faker.datatype.boolean(),
      dateSigned: faker.date.past().toISOString().slice(0, 10),
      createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
      createdBy: faker.string.alpha({ length: { min: 10, max: 20 } }),
      modifiedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
      modifiedBy: faker.string.alpha({ length: { min: 10, max: 20 } }),
    },
    evidence: {
      id: faker.string.uuid(),
      payeIncomeEvidence: faker.datatype.boolean(),
      otherIncomeEvidence: faker.datatype.boolean(),
      housingCostsEvidence: faker.datatype.boolean(),
      capitalEvidence: faker.datatype.boolean(),
      createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
      createdBy: faker.string.alpha({ length: { min: 10, max: 20 } }),
      modifiedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
      modifiedBy: faker.string.alpha({ length: { min: 10, max: 20 } }),
    },
    eligibility: { data: {}, result: {} },
    reasonForReapplication: faker.string.alpha({
      length: { min: 10, max: 20 },
    }),
    meansAssessmentRequired: faker.datatype.boolean(),
    typeOfNonMeans: faker.datatype.boolean(),
    contribution: faker.string.alpha({ length: { min: 10, max: 20 } }),
    scopingQuestions: {},
    applicationType: faker.string.alpha({ length: { min: 10, max: 20 } }),
    createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
    createdBy: faker.string.alpha({ length: { min: 10, max: 20 } }),
    modifiedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
    modifiedBy: faker.string.alpha({ length: { min: 10, max: 20 } }),
    ...overrideResponse,
  }) as MockWithNullableOverrides<Application, O, ApplicationMock>;
