export enum AnswerKey {
  addressLine1 = "addressLine1",
  addressLine2 = "addressLine2",
  addressLine3 = "addressLine3",
  addressLine4 = "addressLine4",
  country = "country",
  county = "county",
  dateOfBirth = "dateOfBirth",
  ecf = "ecf",
  firstName = "firstName",
  hasNINumber = "hasNINumber",
  haveAHomeAddress = "haveAHomeAddress",
  lastName = "lastName",
  legalAidBefore = "legalAidBefore",
  legalAidLast6Months = "legalAidLast6Months",
  niNumber = "niNumber",
  postcode = "postcode",
  reasonForYes = "reasonForYes",
  townOrCity = "townOrCity",
}
