/**
 * Enumeration of HTTP status codes.
 */
export enum HTTP_STATUS {
  // 2xx
  OK = 200,
  CREATED = 201,
  NO_CONTENT = 204,
  // 3xx
  FOUND = 302,
  // 4xx
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  REQUEST_TIMEOUT = 408,
  TOO_MANY_REQUESTS = 429,
  // 5xx
  INTERNAL_SERVER_ERROR = 500,
  BAD_GATEWAY = 502,
  SERVICE_UNAVAILABLE = 503,
  GATEWAY_TIMEOUT = 504,
}

export const {
  BAD_GATEWAY,
  BAD_REQUEST,
  CREATED,
  FORBIDDEN,
  FOUND,
  GATEWAY_TIMEOUT,
  INTERNAL_SERVER_ERROR,
  NO_CONTENT,
  NOT_FOUND,
  OK,
  REQUEST_TIMEOUT,
  SERVICE_UNAVAILABLE,
  TOO_MANY_REQUESTS,
  UNAUTHORIZED,
} = HTTP_STATUS;
